### ISSUE TITLE
Selecting Multiple Elements

### ISSUE THREAD

**Issue by cyouh95** [EditorInThief/prj-rev-bwfs-dasmoto#3]
(Simplify) When you have multiple elements sharing the same properties (such as `font-family: Helvetica;`), you can either combine them like so:

```css
h1, h2, h3, p {
  font-family: "Helvetica";
}
```

https://github.com/EditorInThief/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Art%20Supplies/resources/css/index.css
